service: leviata-api

provider:
  name: google
  runtime: nodejs20
  region: us-central1
  project: ${self:custom.projectIds.${opt:stage, 'dev'}}

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: handler
    events:
      - http: ANY /{proxy+}
    environment:
      # Defina as variáveis de ambiente específicas para o ambiente de desenvolvimento, se necessário

# Configurações específicas para o plugin de autenticação
custom:
  projectIds:
    dev: leviata-api-dev-421000
    homolog: leviata-api-homolog
    preprod: leviata-api-preprod
    prod: leviata-api-prod
  auth:
    regions:
      - us-central1
