service: leviata-api

provider:
  name: google
  runtime: nodejs20
  region: us-central1
  project: leviata-api-dev-421000

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: handler
    events:
      - http: ANY /{proxy+}
    environment:
      # Defina as variáveis de ambiente específicas para o ambiente de desenvolvimento, se necessário

# Configurações específicas para o plugin de autenticação
custom:
  auth:
    regions:
      - us-central1

resources:
  Resources:
    AppIamPolicy:
      Type: 'gcp-types/cloudfunctions-v1:projects.locations.functions.iamPolicy'
      Properties:
        location: us-central1
        function: ${self:service}-${opt:stage}-app
        policy:
          {
            'bindings':
              [
                {
                  'members': ['allUsers'],
                  'role': 'roles/cloudfunctions.invoker',
                },
              ],
          }
