service: leviata-auth-backend

provider:
  name: google
  runtime: nodejs14
  region: us-central1 # Defina a região desejada

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: main
    events:
      - http: path
    environment:
      # GOOGLE_APPLICATION_CREDENTIALS: leviata-auth-backend-18e4f69f3724.json
      # Outras variáveis de ambiente, se necessário

# Configurações específicas para o plugin de autenticação
custom:
  auth:
    regions:
      - us-central1 # ou qualquer região desejada
