service: leviata-api

provider:
  name: google
  runtime: nodejs20
  region: us-central1
  project: leviata-api-dev-421000

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: handler
    events:
      - http: ANY /{proxy+}
    environment:
      # Defina as variáveis de ambiente específicas para o ambiente de desenvolvimento, se necessário
    # Definindo política IAM para permitir acesso público (allUsers) à função
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cloudfunctions:invokeFunction
        Resource: '*'

# Configurações específicas para o plugin de autenticação
custom:
  auth:
    regions:
      - us-central1
