service: leviata-auth-backend

provider:
  name: google
  runtime: nodejs14
  region: us-central1
  project: leviata-auth-backend

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: main
    events:
      - http:
          path: /app # Caminho para o endpoint HTTP
          method: GET # Método HTTP (opcional, padrão: GET)
    environment:
      # Variáveis de ambiente, se necessário

# Configurações específicas para o plugin de autenticação
custom:
  auth:
    regions:
      - us-central1
