service: leviata-auth-backend

provider:
  name: google
  runtime: nodejs14
  region: us-central1
  project: leviata-auth-backend

plugins:
  - serverless-google-cloudfunctions

functions:
  app:
    handler: main
    events:
      - http:
          path: app
          method: get

custom:
  auth:
    regions:
      - us-central1
