name: Terraform Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
      environment:
        description: 'Environment to deploy'
        required: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}

      - name: Plan Terraform
        run: terraform plan ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}

      - name: Apply Terraform
        run: terraform apply -auto-approve ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
