name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Configure Google Cloud credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

      - name: Initialize Terraform
        run: |
          cd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
          terraform init

      - name: Plan Terraform
        run: |
          cd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
          terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
